{  
   'faceId':'e6df3ceb-4e49-4661-8d05-dd78730f51da',
   'faceRectangle':{  
      'top':208,
      'left':228,
      'width':91,
      'height':91
   },
   'faceAttributes':{  
      'smile':1.0,
      'headPose':{  
         'pitch':0.0,
         'roll':4.3,
         'yaw':-0.3
      },
      'gender':'female',
      'age':27.0,
      'facialHair':{  
         'moustache':0.0,
         'beard':0.0,
         'sideburns':0.0
      },
      'glasses':'NoGlasses',
      'emotion':{  
         'anger':0.0,
         'contempt':0.0,
         'disgust':0.0,
         'fear':0.0,
         'happiness':1.0,
         'neutral':0.0,
         'sadness':0.0,
         'surprise':0.0
      },
      'blur':{  
         'blurLevel':'low',
         'value':0.0
      },
      'exposure':{  
         'exposureLevel':'goodExposure',
         'value':0.65
      },
      'noise':{  
         'noiseLevel':'low',
         'value':0.0
      },
      'makeup':{  
         'eyeMakeup':True,
         'lipMakeup':True
      },
      'accessories':[  

      ],
      'occlusion':{  
         'foreheadOccluded':False,
         'eyeOccluded':False,
         'mouthOccluded':False
      },
      'hair':{  
         'bald':0.06,
         'invisible':False,
         'hairColor':[  
            {  
               'color':'brown',
               'confidence':1.0
            },
            {  
               'color':'blond',
               'confidence':0.5
            },
            {  
               'color':'black',
               'confidence':0.34
            },
            {  
               'color':'red',
               'confidence':0.32
            },
            {  
               'color':'gray',
               'confidence':0.14
            },
            {  
               'color':'other',
               'confidence':0.03
            }
         ]
      }
   }
}