# Generated by Django 2.1.2 on 2018-11-03 19:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
